name: Bug report
description: Report a problem with omnibin
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Fill out the form below as completely as possible.

  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: e.g., Pasting PDF from iOS fails with 500
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview of the issue
      description: What happened? Include error messages verbatim if any.
      placeholder: Describe the problem...
    validations:
      required: true

  - type: textarea
    id: desired_fix
    attributes:
      label: How would you like to see this fixed?
      placeholder: Describe the desired behavior or fix approach...
    validations:
      required: true

  - type: dropdown
    id: item_type
    attributes:
      label: Item type
      options:
        - Text
        - Image
        - File
        - Other
    validations:
      required: true

  - type: input
    id: text_length
    attributes:
      label: Character length (if text)
      placeholder: e.g., 12,345

  - type: input
    id: file_size
    attributes:
      label: File size (if image / file)
      placeholder: e.g., 18.2 MB

  - type: textarea
    id: attached_file
    attributes:
      label: File attachment (if file)
      placeholder: If you're comfortable doing so, drag-and-drop the file here, or attach it after creating the issue.

  - type: input
    id: source_platform
    attributes:
      label: Where was the item pasted? (source)
      placeholder: e.g., Desktop PC, Windows 11,Chrome 140.0.7339.129.
      description: Include as much information about device, operating system, browser version, etc.
    validations:
      required: true

  - type: input
    id: destination_platform
    attributes:
      label: Where is it being copied to? (destination)
      placeholder: e.g., iPhone 14 Pro, iOS 17.6.1, app.
      description: Include as much information about device, operating system, browser version, etc.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide numbered steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or screen recordings (optional)
      description: Drag-and-drop images or videos here, or attach them after creating the issue.


