name: Feature request
description: Suggest an idea or improvement for omnibin
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Tell us what you'd like to see in omnibin.

  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: e.g., Support pasting multiple files at once
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What would you like to see implemented/supported in omnibin?
      placeholder: Describe the feature at a high level...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case / user story
      description: Why is this useful? Who benefits?
      placeholder: As a ..., I want ..., so that ...
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Possible approach or details (optional)
      placeholder: Any technical ideas, UX thoughts, or similar products...

  - type: checkboxes
    id: scope
    attributes:
      label: Scope hints (optional)
      options:
        - label: Web app
        - label: iOS app
        - label: iOS share extension
        - label: Windows app

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)

  - type: textarea
    id: additional
    attributes:
      label: Additional context (optional)
      placeholder: Links, mockups, references

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submit checks
      options:
        - label: I have searched for existing issues
          required: true


